spring:
#  sql:
#    init:
#      mode: always
  datasource:
#    url: jdbc:postgresql://localhost:5432/demo_Spring_Boot
#    url: jdbc:h2:file:./src/main/java/com/example/demo;INIT=RUNSCRIPT FROM 'classpath:data.sql'
    url: jdbc:h2:file:./manual_from_lesson/src/main/java/ru/learnUp/db_H2;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
#    url: jdbc:h2:mem:test
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
#    ;DB_CLOSE_DELAY=-1

    username: sa
    password: password

#    driverClassName: org.postgresql.Driver
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL92Dialect
  h2:
    console.enabled: true
    path: /h2-console
#    http://localhost:8080/h2-console

